variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE:latest
  SERVER: ${DEV_SSH_USER}@${DEV_SERVER_HOST} 
  SSH_PRIVATE_KEY: ${DEV_SSH_PRIVATE_KEY}
  PATH_PROJECT: /root/app
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - rollback
build-job:      # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build --no-cache --tag $TAG_COMMIT -f ./app/Dockerfile ./app
    - docker push $TAG_COMMIT
deploy-job:      # This job runs in the build stage, which runs first.
  stage: deploy
  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - apk add --no-cache openssh
    # Create the .ssh directory
    - mkdir -p ~/.ssh
    # Add the SSH private key from the GitLab CI/CD variable
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    # Set the correct permissions for the private key
    - chmod 400 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "Deploying application..."
    - ssh $SERVER "echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin"
    - ssh $SERVER "docker pull $TAG_COMMIT"
    - ssh $SERVER "pwd"
    - scp ./app/* ${SERVER}:/root/app
    - ssh $SERVER "export IMAGE=${TAG_COMMIT}  && cd app && docker rollout -f docker-compose-app.yml service-1"
    - echo "Application successfully deployed."
rooback-job:
  image: docker:latest
  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  stage: rollback
  when: manual
  script:
    - apk add --no-cache openssh
    # Create the .ssh directory
    - mkdir -p ~/.ssh
    # Add the SSH private key from the GitLab CI/CD variable
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    # Set the correct permissions for the private key
    - chmod 400 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "Rolling back the service..."
    - ssh $SERVER "cd $PATH_PROJECT && docker start \$(cat old_container_ids.txt)"
    - ssh $SERVER "cd $PATH_PROJECT && docker start \$(cat old_container_ids.txt)"
    - ssh $SERVER "cd $PATH_PROJECT && docker stop \$(cat new_container_ids.txt)"
    - ssh $SERVER "cd $PATH_PROJECT && docker rm \$(cat new_container_ids.txt)"
    - echo "Rollback completed. Old containers are now running."

