version: "3.7"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
      - ./certificates/acme.json:/etc/traefik/acme/acme.json
